### ISSUE TITLE
C++ implementation

### ISSUE THREAD

**Issue by Isopodus** [krakenrf/gr-krakensdr#6]
Greetings!
I recently got my hands on a KrakenSDR and I wanted to use it with my GNU radio application that I'm writing in C++. I thought it's gonna be an easy deal knowing there is a gr-krakensdr block available, but little did I know its written in Python only.
Therefore:
1. Is there an easy way I can use the compiled .pyc libs in C++ directly?
2. Do you plan on implementing the C++ variant of this block?

I started rewriting the thing on my own, but the effort taken tends to be a time wasted for non-working code, so I decided to ask authors instead.
Thanks in advance!

**Comment by krakenrf** [comment]
Hi, at the moment we have no plans to ever implement a C++ version of the Python code. We are using the Python shared memory interface which makes things easy. In C++ it can get a bit more complex.

There should be a way to access the Python code in C using a wrapper, but I'm not exactly sure how that works.
