### ISSUE TITLE
Various alarming messages from cmake ..

### ISSUE THREAD

**Issue by jabowery** [krakenrf/gr-krakensdr#8]
After upgrade to Ubuntu 24.04.1 LTS, for whatever reason I had to reinstall both gnuradio and KrakenSDR.  Attempting to simply go to my original directory for gr-krakensdr/build and run make or even cmake .. then make did not work properly.  So I deleted gr-krakensdr and recloned the repo.  

This is what happened next with cmake ..

```
~/devel/gr-krakensdr/build$ cmake ..
...
CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/gnuradio/GrPython.cmake:21 (find_package):
  Policy CMP0148 is not set: ...
...

-- Extracting version information from git describe...
**_fatal_**: No names found, cannot describe anything.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- No C++ sources... skipping lib/
<string>:3: SyntaxWarning: invalid escape sequence '\W'
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
```

While I understand the first is merely a "Warning" in combination with the "**_fatal_**" one might be led to Fear Uncertainty and Doubt as to whether unexpected results from one's KrakenSDR were the result of software in addition to the notoriously difficult process of tracking down hardware configuration problems with radio.

**Comment by krakenrf** [comment]
The errors only seem to relate to Doxygen, a system for automatically creating documentation, which we don't use. So they should be fine to ignore.
